### ISSUE TITLE
Install error?

### ISSUE THREAD

**Issue by mesut92** [ludlows/python-pesq#17]
Hi
I tried to install packages. but i got an error as followings. I tried;

```
Build and Install
$ git clone https://github.com/ludlows/python-pesq.git
$ cd python-pesq
$ pip install .  # for python 2
$ pip3 install . # for python 3 
$ cd ..
$ rm -rf python-pesq # remove the code folder since it exists in the python package folder

```
and
```

Install with pip

# PyPi Repository
$ pip install pesq
# The Latest Version
$ pip install https://github.com/ludlows/python-pesq/archive/master.zip
```

Do you have any idea?

```
Processing /media/mesut/Tosun/ses/MetricGAN-master/python-pesq
    ERROR: Command errored out with exit status 1:
     command: /media/mesut/kdtmDisk1/anaconda3/envs/MetricGAN/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-dSS43h/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-dSS43h/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-dSS43h/pip-egg-info
         cwd: /tmp/pip-req-build-dSS43h/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-dSS43h/setup.py", line 32, in <module>
        language="c")
      File "/tmp/pip-req-build-dSS43h/setup.py", line 15, in __init__
        super().__init__(*args, **kwargs)
    TypeError: super() takes at least 1 argument (0 given)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
OS: Ubuntu 18.04

**Comment by ludlows** [comment]
please use the latest version v0.0.2 if you didn't sovle it. 
thanks for using this code.
